name: Test Node.js app - jrdespachante-api

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: '20.x'

            - name: Dependencies install
              run: |
                  yarn

            - name: Tests
              run: |
                  yarn test
